// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var collapsedSearchHeight, grabPadding, header, languageOpen, loginOpen, modal, navigation, navigationHeight, nextSection, search, searchHeight, searchTop;
    languageOpen = false;
    loginOpen = false;
    header = $('#header');
    search = $('#search');
    navigation = $('#navigation');
    navigationHeight = navigation.outerHeight();
    searchHeight = search.outerHeight();
    collapsedSearchHeight = 53;
    searchTop = search.offset();
    nextSection = $('#search').next('section');
    grabPadding = parseInt($('#search').next('section').css('padding-top'));
    $(window).bind('scroll', function(event) {
      var difference, scroll, searchBottom;
      if (window.pageYOffset) {
        scroll = window.pageYOffset;
      } else {
        scroll = document.body.scrollTop;
      }
      if ($('#search').length > 0) {
        $('#search-placeholder').bind('click', function(e) {
          return $('#search-input').focus();
        });
        if ($('body').attr('id') !== 'homepage' && $('body').attr('id') !== 'noun-detail' && $('body').hasClass('drawer-open') === false && $('body').attr('id') !== 'browse') {
          searchBottom = searchTop['top'] + searchHeight;
          if (scroll > searchBottom) {
            search.addClass('fixed');
            nextSection.css({
              'padding-top': searchHeight + grabPadding
            });
            difference = scroll - searchBottom;
            if (scroll > searchTop['top'] && scroll < searchTop['top'] + collapsedSearchHeight + searchHeight) {
              return search.css({
                'top': -collapsedSearchHeight + difference
              });
            } else if (scroll > searchTop['top'] + collapsedSearchHeight) {
              return search.css({
                'top': 0
              });
            }
          } else {
            search.css({
              'top': 0
            });
            nextSection.css({
              'padding-top': grabPadding
            });
            return search.removeClass('fixed');
          }
        }
      }
    });
    return modal = function(location) {
      var modalFile, placement;
      location = location;
      modalFile = location + '.html';
      placement = '#modal';
      return $.get('/modals/' + modalFile, function(data) {
        $(placement).html(data);
        $(placement).fadeIn();
        $('body').addClass('modal-activated');
        $('#modal .close').live().bind('click', function(event) {
          $('body').removeClass('modal-activated');
          return $('#modal').fadeOut();
        });
        if (modalFile === 'checkout.html') {
          $('#credit-card-number input:first').focus();
          $('#credit-card-number input:not(:first)').focus(function(e) {
            var $this, prev;
            $this = $(this);
            prev = $this.prev();
            if ($this.val().length === 0) {
              return $('#credit-card-number input:first').focus();
            }
          });
          return $('#credit-card-number input').keydown(function(e) {
            var $this;
            $this = $(this);
            if (e.shiftKey) {
              e.preventDefault();
            }
            if (e.keyCode === !8 && e.keyCode < 37 || e.keyCode > 57) {
              /*console.log e.keyCode+' key is not valid'
              return false
                        if $this.val().length == 0 and e.keyCode is 8
              $this.prev().focus()
              
                        if $this.val().length == 4 and e.keyCode isnt 8
              ## find the next field
              $this.addClass 'complete'
              $this.next().focus()
              
                      $('#credit-card-number input').keyup (e) -> 
                        $this = $(this)
                        if $this.val().length == 4
              ## find the next field
              $this.addClass 'complete'
              $this.next().focus()
                        else if $this.val().length < 4
              $this.removeClass 'complete'
                        
                        if $this.val().length == 0
              $this.prev().focus()
              
                ## EMAIL UPDATES
                $("#email-updates").submit (e) ->
                  e.preventDefault()
                  $.getJSON @action + "?callback=?", $(this).serialize(), (data) ->
                    if data.Status is 400
                      invalidSubmit = $('#email-updates input').val()
                      $('#email-updates').addClass('shake')
                      $('#email-updates label').text('Sorry, something went wrong with the email address ' + invalidSubmit + '.')
                    else
                      e.preventDefault()
                      justSubmitted = $('#email-updates input').val()
                      $('#email-updates input').val('')
                      # Kill the duplicate text
                      $('#email-placeholder-duplicate').text('')
                      # Hide the Press Enter button
                      $('#email-press-enter').hide()
                      # Show confirm message
                      subscribesvg = '<span class="icon"><!--?xml version="1.0" encoding="utf-8"?--><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="100px" height="64px" viewBox="0 0 100 64" enable-background="new 0 0 100 64" space="preserve"><polygon points="50.001,45.022 50.001,45.023 50,45.022 0,9.464 0,64 100,64 100,9.465 "></polygon><polygon points="99.497,0 0.504,0 50,35.097 "></polygon></svg></span>'
                      $("<a class='confirmation' href='#'>#{subscribesvg}<h1>Subscribed!</h1></a>").insertAfter('#email-updates')
                      $('#footer a.confirmation').fadeIn(200).delay(3000).queue ->
                        $(this).fadeOut(200)
                        $(this).remove()
                        $('#email-updates label').text('Thanks! ' + justSubmitted + ' is now on our mailing list.')
                      $('#footer a.confirmation').bind 'click', (e)->
                        $(this).fadeOut(200)
                        $(this).remove()
              
              
                emailBox = $('#email-updates input')
                ## IE9 fix
                $('#email-placeholder').bind 'click', (e) ->
                  emailBox.focus()
              
                emailBox.bind 'keyup', (e) ->
                ## calculate and add 'press enter' after text
                  emailAddress = emailBox.val()
                  $('#email-placeholder-duplicate').html emailAddress
                  if emailAddress.length < 3
                    $('#email-press-enter').hide()
                  else
                    $('#email-press-enter').fadeIn()
              
              
                ## PLACEHOLDER SHIM
                # Grab the placeholder value
                placeholder = $('#credit-card-number input').attr('placeholder')
                # Set the placeholder to the input value
                $('#credit-card-number-placeholder').html(placeholder)
                # On focus, lose the 
              
              
                ## MODERNIZR PLACEHOLDER FIX
                unless Modernizr.input.placeholder
                  $("[placeholder]").focus(->
                    input = $(this)
                    if input.val() is input.attr("placeholder")
                      input.val ""
                      input.removeClass "placeholder"
                  ).blur(->
                    input = $(this)
                    if input.val() is "" or input.val() is input.attr("placeholder")
                      input.addClass "placeholder"
                      input.val input.attr("placeholder")
                  ).blur()
                  $("[placeholder]").parents("form").submit ->
                    $(this).find("[placeholder]").each ->
                      input = $(this)
                      input.val ""  if input.val() is input.attr("placeholder")
              
              
              ## BACK & FORWARD WITH KEYSTROKES
              $(document).keydown (e) ->
                ## if user presses command & left arrow
                if e.metaKey and e.keyCode is 37
                  history.back(-1)
                if e.metaKey and e.keyCode is 39
                  history.go(1)
              */

            }
          });
        }
      });
    };
  });

}).call(this);
