// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var DOWN, ENTER, UP, exactMatches, minLength, nonexactMatches, searchBox, searchElement, searchResultsDetail;
    searchElement = $('#search');
    searchResultsDetail = $('#results-detail');
    if (searchElement.length > 0) {
      searchBox = searchElement.find('input');
      minLength = 2;
      UP = 38;
      DOWN = 40;
      ENTER = 13;
      $('#search-box .filter').hover(function() {
        return $('.suggest').remove();
      });
      $('#search-box .filter input[type="checkbox"]').change(function() {
        var currentlySelectedFilter;
        currentlySelectedFilter = $(this).val();
        $('.selected-filter .' + currentlySelectedFilter).toggleClass('unchecked');
        if ($('#search-box .filter input[type="checkbox"]:checked').length > 0) {
          $('.filter-by-license').hide();
          $('.selected-filter').show();
          return $('.selected-filter .' + currentlySelectedFilter + ' svg').bind('click', function(event) {
            $('#' + currentlySelectedFilter).attr('checked', false);
            $('.selected-filter .' + currentlySelectedFilter).addClass('unchecked');
            if ($('#search-box .filter input[type="checkbox"]:checked').length === 0) {
              $('.filter-by-license').show();
              return $('.selected-filter').hide();
            }
          });
        } else {
          $('.filter-by-license').show();
          return $('.selected-filter').hide();
        }
      });
      searchBox.bind('keydown', function(e) {
        var searchTerm;
        searchTerm = searchBox.val();
        $('#placeholder-duplicate').html(searchTerm);
        if (searchTerm.length < 3) {
          return $('#press-enter').hide();
        } else {
          return $('#press-enter').fadeIn();
        }
      });
      searchBox.bind('keyup', function(e) {
        var lang, licenseFilter, original, resultFocus, resultFocusIndex, resultFocusParent, resultFocusParentLength, searchItem, searchLabel, searchTerm, suggestedTerm;
        searchTerm = searchBox.val();
        $('#placeholder-duplicate').html(searchTerm);
        if (searchTerm.length < 2) {
          $('#press-enter').hide();
        } else {
          $('#press-enter').fadeIn(400);
        }
        if (e.keyCode === 17 || e.keyCode === 91 || e.keyCode === 9) {

        } else {
          if (e.keyCode === 13) {
            if ($('.result.focus').length > 0) {
              searchItem = $('.result.focus').prop('href');
              searchLabel = 'A Search Even Occurred. The Search was for the noun: ' + searchItem;
              _gaq.push(['_trackEvent', 'Search', 'Noun-Searched', searchLabel]);
              window.location = $('.result.focus a').attr('href');
            } else {
              if (searchTerm.length > 1) {
                if ($('.filter input[type=checkbox]:checked').length > 0) {
                  licenseFilter = '&f=';
                  $('.filter input[type=checkbox]:checked').each(function() {
                    var licenseID, licenseName;
                    licenseName = $(this).attr('name');
                    if (licenseName === 'cc-by') {
                      licenseID = 1;
                    } else {

                    }
                    return licenseFilter = licenseFilter + licenseID;
                  });
                } else {
                  licenseFilter = '';
                }
                searchTerm = searchTerm.toLowerCase();
                lang = '/' + $('html').attr('lang');
                searchLabel = 'A Search Even Occurred. The Search was for the noun: ' + searchTerm;
                _gaq.push(['_trackEvent', 'Search', 'Noun-Searched', searchLabel]);
                window.location = lang + '/search/?q=' + searchTerm + licenseFilter;
              }
            }
          }
          if (e.keyCode === 40 || e.keyCode === 38) {
            if ($('.suggest').length > 0) {
              if ($('.result').hasClass('focus')) {
                $('.result').removeClass('focus');
              }
              if ($('.suggest .suggested-term').length > 0) {
                if (e.keyCode === 40 && $('.suggest .suggested-term').index() + 1 < $('.suggest li').length) {
                  suggestedTerm = $('.suggest .suggested-term').next().text();
                  $('.suggest .suggested-term').removeClass('suggested-term').next().addClass('suggested-term');
                } else if (e.keyCode === 38 && $('.suggest .suggested-term').index() > 0) {
                  suggestedTerm = $('.suggest .suggested-term').prev().text();
                  $('.suggest .suggested-term').removeClass('suggested-term').prev().addClass('suggested-term');
                } else {
                  suggestedTerm = searchBox.data('original');
                  $('.suggest .suggested-term').removeClass('suggested-term');
                }
              } else {
                original = searchBox.val();
                searchBox.data('original', original);
                if (e.keyCode === 40) {
                  suggestedTerm = $('.suggest li:first-child').text();
                  $('.suggest li:first-child').addClass('suggested-term');
                }
              }
              searchBox.val(suggestedTerm.toLowerCase());
              $('#placeholder-duplicate').html(suggestedTerm);
              if (searchBox.val().length < 2) {
                return $('#press-enter').hide();
              }
            } else if ($('#results-detail').length > 0) {
              resultFocus = $('.result.focus');
              resultFocusParent = resultFocus.parent('ul');
              resultFocusIndex = resultFocus.index();
              resultFocusParentLength = resultFocusParent.find('.result').length;
              if (resultFocus.length > 0) {
                if (e.keyCode === 40) {
                  if (resultFocusIndex >= resultFocusParentLength) {
                    resultFocus.removeClass('focus');
                    resultFocusParent.next('ul').find('.result:first').focus().addClass('focus');
                  } else {
                    resultFocus.removeClass('focus').next('.result').focus().addClass('focus');
                  }
                }
                if (e.keyCode === 38) {
                  if (resultFocusIndex <= 1) {
                    resultFocus.removeClass('focus');
                    return resultFocusParent.prev('ul').find('.result:last').focus().addClass('focus');
                  } else {
                    return resultFocus.removeClass('focus').prev('.result').focus().addClass('focus');
                  }
                }
              } else {
                if ($('.result').length > 0) {
                  return $('.result:first').focus().addClass('focus');
                } else {
                  return $('#noun-nonexact-matches .result:first').focus().addClass('focus');
                }
              }
            }
          } else {
            $('.result.focus').removeClass('focus');
            if (searchTerm.length > 1) {
              if ($('.suggest')) {
                $('.suggest').remove();
              }
              return lang = '/' + $('html').attr('lang');
            } else {
              return $('.suggest').remove();
            }
          }
        }
      });
    }
    if (searchResultsDetail.length > 0) {
      exactMatches = $('#noun-exact-matches .result');
      nonexactMatches = $('#noun-nonexact-matches .result');
      return $('body').bind('keydown', function(e) {
        var resultFocus, resultFocusIndex, resultFocusParent, resultFocusParentLength;
        if ($('#search-box input').is(":focus") || $('.suggest').length > 0) {

        } else {
          if (e.keyCode === 13 && $('.result.focus').length > 0) {
            return window.location = $('.result.focus a').attr('href');
          } else {
            $('.suggest').remove();
            resultFocus = $('.result.focus');
            resultFocusParent = resultFocus.parent('ul');
            resultFocusIndex = resultFocus.index();
            resultFocusParentLength = resultFocusParent.find('.result').length;
            if (resultFocus.length > 0) {
              if (e.keyCode === 40) {
                if (resultFocusIndex >= resultFocusParentLength) {
                  resultFocus.removeClass('focus');
                  resultFocusParent.next('ul').find('.result:first').focus().addClass('focus');
                } else {
                  resultFocus.removeClass('focus').next('.result').focus().addClass('focus');
                }
              }
              if (e.keyCode === 38) {
                if (resultFocusIndex <= 1) {
                  resultFocus.removeClass('focus');
                  return resultFocusParent.prev('ul').find('.result:last').focus().addClass('focus');
                } else {
                  return resultFocus.removeClass('focus').prev('.result').focus().addClass('focus');
                }
              }
            } else if (e.keyCode === 40) {
              return $('#noun-exact-matches .result:first').focus().addClass('focus');
            }
          }
        }
      });
    }
  });

}).call(this);
