// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    return $('body').on('click', 'a.drawer', function(e) {
      var $this, body, closeDrawer, drawer, drawerElement, drawerHeight, header, href, otherDrawers;
      e.preventDefault();
      $this = $(this);
      href = $this.attr('href');
      drawer = href.substr(href.lastIndexOf('/') + 1);
      drawerElement = $('#' + drawer);
      body = $('body');
      header = $('#header');
      otherDrawers = $('section.drawer:not(#' + drawer + ')');
      if ($('body').hasClass('drawer-open')) {
        header.css({
          'margin-top': 0
        });
        body.removeClass('drawer-open');
      }
      if (drawerElement.length > 0) {
        $('.drawer').show();
        drawerHeight = $('#' + drawer).outerHeight();
        otherDrawers.css({
          'z-index': -1
        });
        drawerElement.css({
          'z-index': 0
        });
        header.css({
          'margin-top': drawerHeight
        });
        body.addClass('drawer-open');
        $('.close a').bind('click', function(e) {
          e.preventDefault();
          return closeDrawer();
        });
      } else {
        $.get('/drawer/?q=' + drawer, function(html) {
          body.prepend(html);
          if (!Modernizr.input.placeholder) {
            $("[placeholder]").focus(function() {
              var input;
              input = $(this);
              if (input.val() === input.attr("placeholder")) {
                input.val("");
                return input.removeClass("placeholder");
              }
            }).blur(function() {
              var input;
              input = $(this);
              if (input.val() === "" || input.val() === input.attr("placeholder")) {
                input.addClass("placeholder");
                return input.val(input.attr("placeholder"));
              }
            }).blur();
            $("[placeholder]").parents("form").submit(function() {
              return $(this).find("[placeholder]").each(function() {
                var input;
                input = $(this);
                if (input.val() === input.attr("placeholder")) {
                  return input.val("");
                }
              });
            });
          }
          drawerHeight = $('#' + drawer).outerHeight();
          otherDrawers.css({
            'z-index': -1
          });
          header.css({
            'margin-top': drawerHeight
          });
          body.addClass('drawer-open');
          return $('.close a').bind('click', function(e) {
            closeDrawer();
            return e.preventDefault();
          });
        });
      }
      $('body').keyup(function(e) {
        if (e.keyCode === 27) {
          return closeDrawer();
        }
      });
      $(window).bind('scroll', function(event) {
        var scroll;
        scroll = document.body.scrollTop;
        if (scroll > drawerHeight && body.hasClass('drawer-open')) {
          closeDrawer();
          return setTimeout(function() {
            return $('html, body').animate({
              scrollTop: 0
            }, 400);
          }, 10);
        }
      });
      return closeDrawer = function() {
        e.preventDefault();
        header.css({
          'margin-top': 0
        });
        return body.removeClass('drawer-open');
      };
    });
  });

}).call(this);
