// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var moveSlider, updateCurrent, updateDots;
    $('.slider-window').each(function() {
      var $this, browserWidth, currentDot, currentIndex, currentSection, dotContainer, dots, numberOfSlides;
      $this = $(this);
      browserWidth = $(window).width();
      numberOfSlides = $this.find('.slide').length;
      if (numberOfSlides > 1) {
        dots = '';
        currentSection = $('section.current');
        currentIndex = currentSection.find('.slider-container .current-slide').index();
        $this.find('.slide').each(function(i) {
          var currentIfFirst, dot;
          if (i + 1 === 1) {
            currentIfFirst = 'current';
          }
          dot = '<a href="#" class="dot' + i + 1 + ' ' + currentIfFirst + '"> • </a>';
          return dots = dots + dot;
        });
        dotContainer = '<div class="dot-container">' + dots + '</div>';
        $this.append(dotContainer);
        currentDot = currentIndex + 1;
        $this.append('<nav><ul><li class="previous" data-direction="previous"><a href="#"></a></li><li class="next" data-direction="next"><a href="#"></a></li></ul></nav>');
      }
      $this.find('.slider-container').width(browserWidth * numberOfSlides);
      $this.find('.slide').width(browserWidth);
      return $this.find('.slide').css({
        'opacity': '1'
      });
    });
    $('.dot-container a').on('click', function(e) {
      var $this, dotIndex;
      $this = $(this);
      dotIndex = $this.index() + 1;
      return updateCurrent(dotIndex);
    });
    updateDots = function(index) {
      $('.dot-container a').removeClass('current');
      return $('.dot-container a:nth-child(' + index + ')').addClass('current');
    };
    moveSlider = function(direction) {
      var current, currentIndex, currentSection, newSlide, numberOfSlides;
      currentSection = $('section.current');
      numberOfSlides = currentSection.find('.slide').length;
      currentIndex = currentSection.find('.slider-container .current-slide').index();
      current = currentIndex + 1;
      if (direction === 'next' && current + 1 <= numberOfSlides) {
        newSlide = current + 1;
      } else if (direction === 'previous' && current - 1 > 0) {
        newSlide = current - 1;
      } else if (direction === 'next' && current + 1 > numberOfSlides) {
        newSlide = 1;
      } else if (direction === 'previous' && current - 1 === 0) {
        newSlide = numberOfSlides;
      }
      return updateCurrent(newSlide);
    };
    updateCurrent = function(newSlide) {
      var browserWidth, currentSection, newCurrent;
      currentSection = $('section.current');
      newCurrent = newSlide;
      browserWidth = $(window).width();
      currentSection.find('.slider-container .current-slide').removeClass('current-slide');
      currentSection.find('.slider-container .slide:nth-child(' + newCurrent + ')').addClass('current-slide');
      currentSection.find('.dot-container a:nth-child(' + newCurrent + ')').live().addClass('current-slide');
      currentSection.find('.slider-container').css({
        'left': -browserWidth * (newCurrent - 1)
      });
      return updateDots(newSlide);
    };
    $('.slider-window nav li').bind('click', function(e) {
      var direction;
      e.preventDefault;
      if ($(this).parents('section').hasClass('current')) {

      } else {
        $('section.current').removeClass('current');
        $(this).parents('section').addClass('current');
      }
      direction = $(this).data('direction');
      return moveSlider(direction);
    });
    $(document).keydown(function(e) {
      var currentBlock, newBlock;
      currentBlock = $('#navigation .current').index() + 1;
      if (e.keyCode === 39) {
        return moveSlider('next');
      } else if (e.keyCode === 37) {
        return moveSlider('previous');
      } else if (e.keyCode === 38) {
        return newBlock = currentBlock - 1;
      } else if (e.keyCode === 40) {
        return newBlock = currentBlock + 1;
      }
    });
    return $(window).resize(function() {
      return $('.slider-window').each(function() {
        var $this, browserWidth, current, currentIndex, left, numberOfSlides;
        $this = $(this);
        browserWidth = $(window).width();
        numberOfSlides = $this.find('.slide').length;
        $this.find('.slider-container').width(browserWidth * numberOfSlides);
        $this.find('.slide').width(browserWidth);
        currentIndex = $this.find('.current-slide').index();
        current = currentIndex;
        if (current > 0) {
          left = -browserWidth * (current - 1);
        } else {
          left = 0;
        }
        return $this.find('.slider-container').css({
          'left': left
        });
      });
    });
  });

}).call(this);
